basic_settings:
  site_title: Overline
  favicon_image: /images/favicon.png

header_settings:
  logo_image: 
  logo_width: 140

menu_settings:
  menu_items:
    - title: ''
      url: '/'
    - title: 'Work'
      url: '/work'
    - title: 'About'
      url: '/about'
    - title: 'Contact'
      url: '/contact'

grid_settings:
  overlay_opacity: 0.4
  grid_spacing: 32

contact_settings:
  form_action: ''
  confirmation_url: 
  email_subject: 
  send_button_text: 

authors: 
  jt: 
    display_name: JT
    email: jt@overline.studio
    first_name: JT
    last_name: Grauke
    profile_image_class: jt

social_settings:
  facebook_url: ''
  twitter_url: ''
  instagram_url: 'https://www.instagram.com/overline.studio/'
  snapchat_url: ''
  youtube_url: ''
  google-plus_url: ''
  vimeo_url: ''
  pinterest_url: ''
  medium_url: ''
  quora_url: ''
  amazon_url: ''
  apple_url: ''
  android_url: ''
  tumblr_url: ''
  dribbble_url: 'https://www.dribbble.com/jtgrauke/'
  behance_url: ''
  deviantart_url: ''
  github_url: ''
  reddit_url: ''
  flickr_url: ''
  etsy_url: ''
  kickstarter_url: ''
  soundcloud_url: ''
  spotify_url: ''
  bandcamp_url: ''
  linkedin_url: 'https://www.linkedin.com/company/overlinestudio/'

color_settings:
  background_color: '#FFFFFF'
  background_alt_color: '#F3F3F4'
  text_dark_color: '#000000'
  text_medium_color: '#999999'
  text_light_color: '#DDDDDD'
  accent_color: '#1F69FF'
  border_color: '#CCCCCC'
  overlay_background_color: '#000000'
  overlay_text_color: '#ffffff'
  overlay_accent_color: '#000000'
  error_color: '#FE4531'

font_settings:
  font_embed: ''
  title_font: '"Helvetica", sans-serif'
  body_font: '"Helvetica", sans-serif'
  detail_font: '"Inconsolata", Menlo, monospace'
  regular_weight: 400
  bold_weight: 600

advanced_settings:
  ajax_loading: false
  analytics_code: ""
  header_js: ""
  footer_js: ""